spring.application.name=march-24-1sb
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/ticket_res_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Dhak$hna02

#setting hiberante auto
spring.jpa.hibernate.ddl-auto = update
spring.jpa.hibernate.show.sql=true
logging.level.org.springframework.security=DEBUG

#Security props

